//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Maintenance
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Maintenance()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Maintenance", typeof(Maintenance).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;p&gt;Accessing the site during this time may result in loss of data. &lt;/p&gt;&lt;p class=&quot;last&quot;&gt;We thank you for your patience.&lt;/p&gt;.
		/// </summary>
		public static string MaintenanceMsg1HourCopy
		{
			get
			{
				return ResourceManager.GetString("MaintenanceMsg1HourCopy", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Site maintenance is due to start in {0} minutes and is scheduled to last approximately {1} minutes..
		/// </summary>
		public static string MaintenanceMsg1HourTitle
		{
			get
			{
				return ResourceManager.GetString("MaintenanceMsg1HourTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;p&gt;Please do not access the site during this time as you may lose any unsaved data.&lt;/p&gt;&lt;p class=&quot;last&quot;&gt;We are sorry for any inconvenience this may cause and we thank you for your patience.&lt;/p&gt;.
		/// </summary>
		public static string MaintenanceMsg24HourCopy
		{
			get
			{
				return ResourceManager.GetString("MaintenanceMsg24HourCopy", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Please note that site maintenance will take place from &lt;br /&gt;&lt;span class=&quot;delivery-start-time&quot;&gt;{0:HH:mm} GMT&lt;/span&gt; on &lt;span class=&quot;delivery-date&quot;&gt;{0:d MMM yyyy}&lt;/span&gt;.
		/// </summary>
		public static string MaintenanceMsg24HourTitle
		{
			get
			{
				return ResourceManager.GetString("MaintenanceMsg24HourTitle", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;p&gt;Maintenance is expected to be complete in about &lt;span class=&quot;delivery-end-countdown&quot;&gt;{0} minutes&lt;/span&gt;&lt;/p&gt;&lt;p class=&quot;last&quot;&gt;Thank you for your patience and we’ll be back online soon.&lt;/p&gt;.
		/// </summary>
		public static string MaintenanceMsgDeliveryHourCopy
		{
			get
			{
				return ResourceManager.GetString("MaintenanceMsgDeliveryHourCopy", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;em&gt;Important! The site is currently undergoing maintenance.&lt;/em&gt; &lt;br /&gt;Please do not access the site right now as you may lose any unsaved data..
		/// </summary>
		public static string MaintenanceMsgDeliveryHourTitle
		{
			get
			{
				return ResourceManager.GetString("MaintenanceMsgDeliveryHourTitle", resourceCulture);
			}
		}
	}
}
